eureka:
  client:
    serviceUrl:
#      defaultZone: "http://localhost:8010/eureka/"
       defaultZone: http://eureka-primary:8010/eureka/, http://eureka-secondary:8010/eureka/, http://eureka-tetriary:8010/eureka/
