eureka:
  client:
    serviceUrl:
#      defaultZone: "http://localhost:8010/eureka/"
       defaultZone: http://eureka-primary:8010/eureka/,http://eureka-secondary:8011/eureka/,http://eureka-tertiary:8012/eureka/
       
spring:
  zipkin:
    base-url: "http://localhost:9411"
  sleuth:
    sampler:
      probability: 1.0
